#!/usr/bin/env python3
"""
Generate a runnable HoloViz data-to-viz skeleton from a tabular inventory.
"""

import argparse
import json
from pathlib import Path


TEMPLATE = """#!/usr/bin/env python3
\"\"\"
Auto-generated HoloViz data-to-viz skeleton.

This script is intended as a starting point. It will:
- read existing tabular data only
- export HTML apps into an apps directory
- optionally write viz_manifest.json when run with --manifest

To run:
  uv run --with __UV_DEPS__ -s auto_data_to_viz.py --mode __MODE__ --apps-dir "__APPS_DIR__" --manifest viz_manifest.json

Notes:
- Geo mode inlines Panel/Bokeh assets, but tile-backed basemaps may still require network access at view time unless you replace or pre-cache them.
- Large-data hints require datashader in the execution environment.
\"\"\"

import argparse
import json
import os
import shutil
from pathlib import Path

import holoviews as hv
import hvplot.pandas  # noqa: F401
import pandas as pd
import panel as pn
from bokeh.resources import INLINE


DEFAULT_MAX_ITEMS = __MAX_ITEMS__
DEFAULT_MODE = "__MODE__"
INVENTORY_JSON = r'''__INVENTORY_JSON__'''
INVENTORY = json.loads(INVENTORY_JSON)


def _ensure_apps_dir(apps_dir: Path, clean: bool) -> Path:
    if not apps_dir.is_absolute():
        apps_dir = (Path(os.getcwd()) / apps_dir).resolve()
    else:
        apps_dir = apps_dir.resolve()

    if clean:
        cwd = Path(os.getcwd()).resolve()
        if cwd not in apps_dir.parents:
            raise RuntimeError(f"Refusing to clean apps outside CWD: {apps_dir}")
        if apps_dir.exists():
            shutil.rmtree(apps_dir)

    apps_dir.mkdir(parents=True, exist_ok=True)
    return apps_dir


def _resolve_path(entry: dict) -> Path:
    if entry.get("abs_path"):
        candidate = Path(entry["abs_path"])
        if candidate.exists():
            return candidate
    base_dir = INVENTORY.get("base_dir") or os.getcwd()
    return Path(base_dir) / entry.get("rel_path", "")


def _read_entry(entry: dict) -> pd.DataFrame:
    path = _resolve_path(entry)
    file_format = entry.get("file_format")
    if file_format == "csv":
        return pd.read_csv(path)
    if file_format == "tsv":
        return pd.read_csv(path, sep="\\t")
    if file_format == "jsonl":
        return pd.read_json(path, lines=True)
    if file_format == "json":
        return pd.read_json(path)
    raise RuntimeError(f"Unsupported format: {file_format}")


def _sanitize_stem(text: str) -> str:
    out: list[str] = []
    for char in text.lower():
        if char.isalnum():
            out.append(char)
        elif char in {" ", "_", "-", "."}:
            out.append("-")
    return "".join(out).strip("-") or "visualization"


def _pick_title(entry: dict) -> str:
    return Path(entry.get("rel_path") or "visualization").stem.replace("_", " ").replace("-", " ")


def _build_view(entry: dict, data_frame: pd.DataFrame, mode: str):
    title = _pick_title(entry)
    x_column = entry.get("likely_x")
    y_column = entry.get("likely_y")
    group_column = entry.get("likely_group")
    lat_column = entry.get("likely_lat")
    lon_column = entry.get("likely_lon")
    large_hint = bool(entry.get("large_dataset_hint"))

    hv.extension("bokeh")
    pn.extension()

    if large_hint:
        try:
            import datashader  # noqa: F401
        except Exception as exc:
            raise RuntimeError(
                "large_dataset_hint requires datashader. Re-run with: uv run --with pandas,hvplot,holoviews,panel,bokeh,datashader ..."
            ) from exc

    if mode == "geo":
        try:
            import geoviews as gv
        except Exception as exc:
            raise RuntimeError(
                "Geo mode requires geoviews and cartopy. Re-run with: uv run --with pandas,hvplot,holoviews,panel,bokeh,geoviews,cartopy ..."
            ) from exc

        gv.extension("bokeh")
        if not lat_column or not lon_column:
            raise RuntimeError("Geo mode requires likely_lat and likely_lon")
        point_kwargs = {
            "x": lon_column,
            "y": lat_column,
            "geo": True,
            "tiles": "OSM",
            "hover_cols": list(data_frame.columns[:8]),
            "frame_width": 800,
            "frame_height": 500,
            "datashade": large_hint,
        }
        if group_column:
            point_kwargs["color"] = group_column
        plot = data_frame.hvplot.points(**point_kwargs)
        view = pn.template.FastListTemplate(
            title=title,
            main=[plot],
            sidebar=[pn.pane.Markdown("Geo exploration generated by the data-to-viz skill.")],
        )
        return view, "map", "interactive"

    if x_column and y_column and "evolution" in entry.get("recommended_chart_families", []):
        line_kwargs = {
            "x": x_column,
            "y": y_column,
            "frame_width": 780,
            "frame_height": 420,
            "rasterize": large_hint,
            "title": title,
        }
        if group_column:
            line_kwargs["by"] = group_column
        plot = data_frame.hvplot.line(**line_kwargs)
        chart_family = "evolution"
    elif x_column and y_column:
        scatter_kwargs = {
            "x": x_column,
            "y": y_column,
            "frame_width": 780,
            "frame_height": 420,
            "datashade": large_hint,
            "title": title,
        }
        if group_column:
            scatter_kwargs["by"] = group_column
        plot = data_frame.hvplot.scatter(**scatter_kwargs)
        chart_family = "correlation"
    elif y_column:
        hist_kwargs = {
            "y": y_column,
            "frame_width": 780,
            "frame_height": 420,
            "title": title,
        }
        if group_column:
            hist_kwargs["by"] = group_column
        plot = data_frame.hvplot.hist(**hist_kwargs)
        chart_family = "distribution"
    else:
        category = entry.get("categorical_columns", [None])[0]
        if category is None:
            raise RuntimeError("No plottable columns found")
        counts = data_frame[category].value_counts(dropna=False).rename_axis(category).reset_index(name="count")
        plot = counts.hvplot.bar(x=category, y="count", frame_width=780, frame_height=420, title=title)
        chart_family = "comparison/ranking"

    if mode == "app":
        table = pn.pane.DataFrame(data_frame.head(20), sizing_mode="stretch_width")
        view = pn.template.FastListTemplate(
            title=title,
            main=[plot, table],
            sidebar=[pn.pane.Markdown("Interactive report app generated by the data-to-viz skill.")],
        )
        return view, chart_family, "interactive"

    view = pn.template.FastListTemplate(
        title=title,
        main=[plot],
        sidebar=[pn.pane.Markdown("Interactive exploration generated by the data-to-viz skill.")],
    )
    return view, chart_family, "interactive"


def main() -> int:
    ap = argparse.ArgumentParser(description="Run the auto HoloViz data-to-viz script.")
    ap.add_argument("--apps-dir", default="__APPS_DIR__", help="Output apps directory.")
    ap.add_argument("--mode", default=DEFAULT_MODE, choices=["explore", "geo", "app"], help="Routing mode.")
    ap.add_argument("--clean", action="store_true", help="Clean apps-dir before exporting.")
    ap.add_argument("--max-items", type=int, default=DEFAULT_MAX_ITEMS, help="Max inventory entries to render.")
    ap.add_argument("--manifest", default=None, help="Optional viz_manifest.json output path.")
    args = ap.parse_args()

    apps_dir = _ensure_apps_dir(Path(args.apps_dir), clean=bool(args.clean))
    entries = INVENTORY.get("entries", [])
    if not isinstance(entries, list):
        raise RuntimeError("INVENTORY.entries must be a list")

    items: list[dict[str, object]] = []
    total = max(0, min(int(args.max_items), len(entries)))
    for index in range(total):
        entry = entries[index]
        try:
            data_frame = _read_entry(entry)
            view, chart_family, interaction_level = _build_view(entry, data_frame, args.mode)
            title = _pick_title(entry)
            stem = f"{index + 1:02d}-{_sanitize_stem(title)}"
            html_path = apps_dir / f"{stem}.html"
            view.save(html_path, resources=INLINE, embed=False)
            items.append(
                {
                    "id": f"viz-{index + 1:02d}",
                    "filename": html_path.name,
                    "preview_filename": None,
                    "title": title,
                    "plot_system": "holoviz",
                    "chart_family": chart_family,
                    "task_mode": args.mode,
                    "interaction_level": interaction_level,
                    "script_path": Path(__file__).name,
                    "data_sources": [str(_resolve_path(entry))],
                    "caption_suggestion": f"Interactive {chart_family} view of {title}. Replace with a task-specific description before sharing.",
                    "notes": (
                        "Panel/Bokeh assets are inlined, but tile-backed basemaps may still require network access at view time."
                        if args.mode == "geo"
                        else "Large-data rendering enabled; datashader is required in the execution environment."
                        if entry.get("large_dataset_hint")
                        else None
                    ),
                }
            )
        except Exception as exc:
            print(f"[WARN] View {index + 1} failed: {exc}")

    if args.manifest:
        manifest_path = Path(args.manifest).expanduser().resolve()
        manifest_obj = {
            "generated_at": INVENTORY.get("generated_at"),
            "figures_dir": None,
            "apps_dir": str(apps_dir),
            "visualizations": items,
        }
        manifest_path.write_text(json.dumps(manifest_obj, indent=2), encoding="utf-8")
        print(f"[OK] Wrote manifest: {manifest_path}")

    print(f"[OK] Wrote apps to: {apps_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate auto_data_to_viz.py HoloViz skeleton.")
    ap.add_argument("--inventory", required=True, help="Input inventory JSON from tabular_inventory.py.")
    ap.add_argument("--mode", required=True, choices=["explore", "geo", "app"], help="HoloViz routing mode.")
    ap.add_argument("--out", required=True, help="Output path for auto_data_to_viz.py.")
    ap.add_argument("--apps-dir", default="apps", help="Apps directory (default: apps).")
    ap.add_argument("--max-items", type=int, default=6, help="Max inventory entries the script will attempt.")
    args = ap.parse_args(argv)

    inv_path = Path(args.inventory).expanduser().resolve()
    try:
        inv = json.loads(inv_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"[ERROR] Failed to read inventory JSON: {inv_path}: {exc}")
        return 2

    entries = inv.get("entries", [])
    if not isinstance(entries, list):
        print("[ERROR] inventory.entries must be a list")
        return 2

    embedded = {
        "base_dir": inv.get("base_dir"),
        "generated_at": inv.get("generated_at"),
        "entries": [
            {
                "rel_path": entry.get("rel_path"),
                "abs_path": entry.get("abs_path"),
                "file_format": entry.get("file_format"),
                "numeric_columns": entry.get("numeric_columns", []),
                "categorical_columns": entry.get("categorical_columns", []),
                "likely_x": entry.get("likely_x"),
                "likely_y": entry.get("likely_y"),
                "likely_group": entry.get("likely_group"),
                "likely_lat": entry.get("likely_lat"),
                "likely_lon": entry.get("likely_lon"),
                "large_dataset_hint": entry.get("large_dataset_hint", False),
                "recommended_chart_families": entry.get("recommended_chart_families", []),
            }
            for entry in entries
            if isinstance(entry, dict) and (entry.get("rel_path") or entry.get("abs_path"))
        ],
    }

    uv_deps = ["pandas", "hvplot", "holoviews", "panel", "bokeh"]
    if args.mode == "geo":
        uv_deps.extend(["geoviews", "cartopy"])
    if any(bool(entry.get("large_dataset_hint")) for entry in embedded["entries"]):
        uv_deps.append("datashader")

    inventory_json = json.dumps(embedded, indent=2)
    script = (
        TEMPLATE.replace("__APPS_DIR__", args.apps_dir)
        .replace("__MODE__", args.mode)
        .replace("__MAX_ITEMS__", str(int(args.max_items)))
        .replace("__UV_DEPS__", ",".join(uv_deps))
        .replace("__INVENTORY_JSON__", inventory_json)
    )

    out_path = Path(args.out).expanduser().resolve()
    out_path.write_text(script, encoding="utf-8")
    print(f"[OK] Wrote skeleton: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
